Merged patches-2_2 branch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7746,27 +7746,24 @@ if test "$qt" = "yes"; then
   echo "$as_me:$LINENO: checking for Qt include files" >&5
 echo $ECHO_N "checking for Qt include files... $ECHO_C" >&6
   if test "$QTDIR" != ""; then
-    if test -f $QTDIR'/include/qapp.h'; then
+    if test -f $QTDIR'/include/qapplication.h'; then
       QTINCLUDE=$QTDIR'/include'
     fi
   fi
   if test "$QTINCLUDE" = ""; then
-    if test -f '/usr/lib/qt3/include/qapp.h'; then
+    if test -f '/usr/lib/qt3/include/qapplication.h'; then
       QTINCLUDE='/usr/lib/qt3/include'
       QTDIR='/usr/lib/qt3'
-    elif test -f '/usr/lib/qt2/include/qapp.h'; then
-      QTINCLUDE='/usr/lib/qt2/include'
-      QTDIR='/usr/lib/qt2'
-    elif test -f '/usr/include/qt3/qapp.h'; then
+    elif test -f '/usr/include/qt3/qapplication.h'; then
       QTINCLUDE='/usr/include/qt3'
-    elif test -f '/usr/include/qt/qapp.h'; then
+    elif test -f '/usr/include/qt/qapplication.h'; then
       QTINCLUDE='/usr/include/qt'
-    elif test -f '/usr/local/include/qt/qapp.h'; then
+    elif test -f '/usr/local/include/qt/qapplication.h'; then
       QTINCLUDE='/usr/local/include/qt'
-    elif test -f '/usr/local/qt2/include/qapp.h'; then
-      QTINCLUDE='/usr/local/qt2/include'
-      QTDIR='/usr/local/qt2'
-    elif test -f '/usr/local/qt/include/qapp.h'; then
+    elif test -f '/usr/local/qt3/include/qapplication.h'; then
+      QTINCLUDE='/usr/local/qt3/include'
+      QTDIR='/usr/local/qt3'
+    elif test -f '/usr/local/qt/include/qapplication.h'; then
       QTINCLUDE='/usr/local/qt/include'
       QTDIR='/usr/local/qt'
     fi
@@ -7782,19 +7779,22 @@ echo "$as_me: error: Cannot find Qt; either define QTDIR or use --without-qt" >&
 echo "${ECHO_T}$QTINCLUDE" >&6
   fi
 
-  ac_ext=cc
+  for lib in qt-mt qt; do
+    if test "$QTLIB" = ""; then
+      ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-  echo "$as_me:$LINENO: checking for qApp in -lqt-mt" >&5
-echo $ECHO_N "checking for qApp in -lqt-mt... $ECHO_C" >&6
-if test "${ac_cv_lib_qt_mt_qApp+set}" = set; then
+      as_ac_Lib=`echo "ac_cv_lib_$lib''_qApp" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for qApp in -l$lib" >&5
+echo $ECHO_N "checking for qApp in -l$lib... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lqt-mt  $LIBS"
+LIBS="-l$lib  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -7838,120 +7838,56 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_qt_mt_qApp=yes
+  eval "$as_ac_Lib=yes"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_qt_mt_qApp=no
+eval "$as_ac_Lib=no"
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_qt_mt_qApp" >&5
-echo "${ECHO_T}$ac_cv_lib_qt_mt_qApp" >&6
-if test $ac_cv_lib_qt_mt_qApp = yes; then
-  QTLIB='-lqt-mt'
-else
-  echo "$as_me:$LINENO: checking for qApp in -lqt" >&5
-echo $ECHO_N "checking for qApp in -lqt... $ECHO_C" >&6
-if test "${ac_cv_lib_qt_qApp+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lqt  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char qApp ();
-int
-main ()
-{
-qApp ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_qt_qApp=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_qt_qApp=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_qt_qApp" >&5
-echo "${ECHO_T}$ac_cv_lib_qt_qApp" >&6
-if test $ac_cv_lib_qt_qApp = yes; then
-  QTLIB='-lqt'
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
+if test `eval echo '${'$as_ac_Lib'}'` = yes; then
+  QTLIB="-l$lib"
 fi
 
-fi
-
-  ac_ext=c
+      ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-  if test "$QTLIB" = ""; then
-    echo "$as_me:$LINENO: checking for Qt library path" >&5
-echo $ECHO_N "checking for Qt library path... $ECHO_C" >&6
-    if test -f $QTDIR'/lib/libqt.a'; then
-      QTLIB='-L'$QTDIR'/lib -lqt'
-    fi
-    if test "$QTLIB" = ""; then
-      if test -f '/usr/local/lib/libqt.a'; then
-        QTLIB='-L/usr/local/lib -lqt'
-      elif test -f '/usr/local/qt/lib/libqt.a'; then
-        QTLIB='-L/usr/local/qt/lib -lqt'
+      if test "$QTLIB" = ""; then
+        echo "$as_me:$LINENO: checking for $QTLIB library path" >&5
+echo $ECHO_N "checking for $QTLIB library path... $ECHO_C" >&6
+        if test -f $QTDIR'/lib/lib$lib.a'; then
+          QTLIB='-L'$QTDIR'/lib -l$lib'
+        fi
+        if test "$QTLIB" = ""; then
+          if test -f '/usr/local/lib/lib$lib.a'; then
+            QTLIB='-L/usr/local/lib -l$lib'
+          elif test -f '/usr/local/qt/lib/lib$lib.a'; then
+            QTLIB='-L/usr/local/qt/lib -l$lib'
+          fi
+        fi
+        if test "$QTLIB" = ""; then
+          echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        else
+          echo "$as_me:$LINENO: result: $QTLIB" >&5
+echo "${ECHO_T}$QTLIB" >&6
+        fi
       fi
     fi
-    if test "$QTLIB" = ""; then
-      echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-      { { echo "$as_me:$LINENO: error: Cannot find libqt.a; either define QTDIR or use --without-qt" >&5
-echo "$as_me: error: Cannot find libqt.a; either define QTDIR or use --without-qt" >&2;}
+  done
+  if test "$QTLIB" = ""; then
+    { { echo "$as_me:$LINENO: error: Cannot find libqt-mt.a or libqt.a; either define QTDIR or use --without-qt" >&5
+echo "$as_me: error: Cannot find libqt-mt.a or libqt.a; either define QTDIR or use --without-qt" >&2;}
    { (exit 1); exit 1; }; }
-    else
-      echo "$as_me:$LINENO: result: $QTLIB" >&5
-echo "${ECHO_T}$QTLIB" >&6
-    fi
   fi
 
   # Extract the first word of "moc", so it can be a program name with args.
